### PR TITLE
mobile deep linking

### PR DESCRIPTION
**Pull request by alanthai**
Adds mobile deep linking

Ticket: https://github.com/Shopify/shopify-cli-extensions/issues/109

# 🎩  instructions

- Checkout this branch
- Install go if you haven't already `brew install go`
- Build and run the dev server `make bootstrap`, then `make run serve testdata/shopifile.yml`

    - **Check server has a store prop**
    Screen Shot 2021-10-27 at 9 09 35 AM

- Start the app `yarn start`
    - **Check the mobile link by clicking the mobile icon. Click "Copy link"
    Screen Shot 2021-10-27 at 9 10 58 AM
    - You should see a link like `https://test-shop.myshopify.com/extensions-dev/mobile?url=http://localhost:8000/extensions/00000000-0000-0000-0000-000000000000`

### CODE REVIEW

**Comment by james-woo** [comment]
> > Should the mobile?url endpoint be accessible and provide JSON? Right now I am seeing tunnel not found. Mobile will be performing a fetch on this url, so I expected some fake JSON payload or something.
> 
> @james-woo You can't go directly to the link. I think when they paste it on mobile, we leave it to mobile app to handle the endpoint right?
> 
> cc: @vividviolet

Mobile will perform a get request at `http://localhost:8000/extensions/00000000-0000-0000-0000-000000000000`, so this is the responsibility of the dev server.

**Comment by vividviolet** [comment]
Yes, Mobile needs to fetch from the provided url. @james-woo you need to be using the ngrok url, localhost will not work. Can you run this with a tunnel and check? You should get a JSON response

**Comment by vividviolet** [comment]
@alanthai perhaps we need need to turn off the QR code option or display an error if the dev console is accessed via localhost to avoid issues?

**Comment by alanthai** [comment]
> @alanthai perhaps we need need to turn off the QR code option or display an error if the dev console is accessed via localhost to avoid issues?

@vividviolet Good idea

**Review by james-woo — APPROVED** [review]
🎩  I can see the JSON payload at something like `https://6e4a-38-26-23-211.ngrok.io/extensions/00000000-0000-0000-0000-000000000001`, one thing I noticed is that it performs a redirect (308 permanent redirect) when I paste that into my browser.

**Comment by vividviolet** [comment]
@james-woo yup, the redirect is expected as it's supposed to bring you to the extension in your dev store. See this ticket for more info:https://github.com/Shopify/shopify-cli-extensions/issues/53

**Pull request merged**
